### ISSUE TITLE
[M2] RuntimeError: PyTorch is not linked with support for mps devices

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/reranker#4]
Running on macOS M2, I'm seeing this after a while
```
[+] Running 1/0
 ✔ Container reranker  Created                                                                                        0.0s 
Attaching to reranker
reranker  | INFO:     port: 8787
reranker  | INFO:     max_length: 1024
reranker  | INFO:     model: BAAI/bge-reranker-v2-m3
reranker  | INFO:     device: mps
reranker  | Traceback (most recent call last):
reranker  |   File "/usr/local/bin/uvicorn", line 8, in <module>
reranker  |     sys.exit(main())
reranker  |              ^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
reranker  |     return self.main(*args, **kwargs)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
reranker  |     rv = self.invoke(ctx)
reranker  |          ^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
reranker  |     return ctx.invoke(self.callback, **ctx.params)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
reranker  |     return __callback(*args, **kwargs)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
reranker  |     run(
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
reranker  |     server.run()
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
reranker  |     return asyncio.run(self.serve(sockets=sockets))
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
reranker  |     return runner.run(main)
reranker  |            ^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
reranker  |     return self._loop.run_until_complete(task)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
reranker  |     await self._serve(sockets)
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
reranker  |     config.load()
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
reranker  |     self.loaded_app = import_from_string(self.app)
reranker  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
reranker  |     module = importlib.import_module(module_str)
reranker  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
reranker  |     return _bootstrap._gcd_import(name[level:], package, level)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
reranker  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
reranker  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
reranker  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
reranker  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
reranker  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
reranker  |   File "/app/main.py", line 35, in <module>
reranker  |     model = model.to(device)
reranker  |             ^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2724, in to
reranker  |     return super().to(*args, **kwargs)
reranker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
reranker  |     return self._apply(convert)
reranker  |            ^^^^^^^^^^^^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
reranker  |     module._apply(fn)
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
reranker  |     module._apply(fn)
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
reranker  |     module._apply(fn)
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
reranker  |     param_applied = fn(param)
reranker  |                     ^^^^^^^^^
reranker  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
reranker  |     return t.to(
reranker  |            ^^^^^
reranker  | RuntimeError: PyTorch is not linked with support for mps devices
```

**Comment by s-kostyaev** [comment]
Try to reinstall pytorch according to this instructions  https://developer.apple.com/metal/pytorch/

**Comment by oatmealm** [comment]
I'm running it in a container... just realized it's actually not supported, is it? Any way, brew can install it with mps support I guess I'll run it natively and see.

**Comment by s-kostyaev** [comment]
Docker doesn't support mps

**Comment by s-kostyaev** [comment]
@oatmealm can we close this issue?
